### ISSUE TITLE
Update to latest Anki version

### ISSUE THREAD

**Issue by sr258** [ppd/anki-ppd#4]
Hi,

Great that you've put Anki onto the Snap Store. Is it possible to upgrade Anki to the latest version in the Snap or is the Core 22 snap still not out yet?

**Comment by ppd** [comment]
The problem is that I'm waiting for the core22 version of the KDE neon content snap and extension. I'm involved with the KDE snaps to speed things up, but as of now, KDE neon for jammy hasn't even been released yet, and 22.04.1, the base for the new KDE neon, has been postponed by Canonical for a week.

I might spin up a beta version with Qt included in the snap itself. That could be temporary measure till the Qt situation gets sorted out; I know of tentative plans to maintain a Qt content snap by Canonical themselves.

**Comment by ppd** [comment]
@sr258 Try the build from `beta`: `snap refresh anki-ppd --beta`.
It's the aforementioned stopgap solution.

**Comment by sr258** [comment]
@ppd Thanks for working on this! It works great so far. Anki even respects the Ubuntu 22.04 theme now!

**Comment by ppd** [comment]
I might publish this as stable until we get the KDE extension for core22. Please report back in a while when you're confident that everything's in order; I'm not personally using Anki anymore, so I'm not a good beta tester.

**Comment by sr258** [comment]
@ppd Alright, I will do that!

**Comment by sr258** [comment]
@ppd I've used your Snap beta version for two weeks now and I haven't encountered any issues. Looks like it works as expected.

**Comment by ppd** [comment]
> Released 'anki-ppd' revision 8 to channels: 'stable'

**Comment by sr258** [comment]
@ppd Thanks a lot for maintaining the snap!
